Add subtract ability to PeriodCollection
spatie/period pull request #84
Opened 2021-03-19 15:37 UTC by masterix21

2021-03-23 14:47 UTC, brendt commented
Could you add a doc block like this one to the test? https://github.com/spatie/period/blob/master/tests/PeriodCollectionTest.php#L13-L20

2021-03-23 18:03 UTC, masterix21 commented
Done :)

2021-03-24 04:38 UTC, brendt requested changes

2021-03-24 04:38 UTC, brendt commented on src/PeriodCollection.php
> +    public function subtract(PeriodCollection|Period $periods)
I've been trying to apply the naming convention to call these other periods `$others` and `$other` in all methods, could you change the variable names?

2021-03-24 04:38 UTC, brendt commented on src/PeriodCollection.php
> +            $periods = new self($periods);
Change to `new static()` so that it also works if someone extends from the `PeriodCollection` class

2021-03-24 04:38 UTC, brendt commented on src/PeriodCollection.php
> +        $collection = new self();
Also change to `new static()`

2021-03-24 04:38 UTC, brendt commented on src/PeriodCollection.php
> +    public function subtract(PeriodCollection|Period $periods)
Also add `: static` return type

2021-03-24 04:38 UTC, brendt commented on tests/PeriodCollectionTest.php
> +        $this->assertEquals(0, $result->overlapAll(new PeriodCollection($removePeriod))->count());
Use hard coded date assertions here instead. Tip: you can use something like `$this->assertTrue(Period::fromString('[1987-02-01,1987-02-19]')->equals($result[0])`

2021-03-24 04:38 UTC, brendt commented on tests/PeriodCollectionTest.php
> +        $this->assertEquals(0, $result->overlapAll($removePeriods)->count());
Also use hard coded date assertions

2021-03-24 09:02 UTC, brendt approved these changes

2021-03-24 09:02 UTC, merged

2021-03-24 09:02 UTC, brendt commented
Awesome, thanks!

2021-03-24 09:08 UTC, brendt commented
Released as 2.1.0: https://github.com/spatie/period/releases/tag/2.1.0